apps:
  mutt-oauth2:
    command: 'bin/mutt-oauth2'
    plugs:
      - 'home'
      - 'network'
      - 'network-bind'
base: 'core24'
confinement: 'strict'
contact: 'https://github.com/Tatsh/mutt-oauth2/issues'
description: 'Packaged, maintained version of contributed mutt_oauth2.py script.'
donation: 'https://buymeacoffee.com/Tatsh'
grade: 'stable'
issues: 'https://github.com/Tatsh/mutt-oauth2/issues'
license: 'MIT'
name: 'mutt-oauth2'
parts:
  mutt-oauth2:
    build-packages: []
    plugin: 'python'
    python-packages:
      - '.'
    source: '.'
    stage-packages: []
platforms:
  amd64:
    build-on: 'amd64'
  arm64:
    build-on: 'arm64'
source-code: 'https://github.com/Tatsh/mutt-oauth2'
summary: 'Packaged, maintained version of contributed mutt_oauth2.py script.'
title: 'mutt-oauth2'
version: '0.1.2'
website: 'https://tatsh.github.io/mutt-oauth2/'
